### ISSUE TITLE
user login

### ISSUE THREAD

**Issue by MakenHubbard** [nss-evening-cohort-7/nutshell-adobe-bricks#9]
## Story 
As a user, In order to love everything that is Nutshell, I need to be able to log in 

## Acceptance Criteria
Given a user wants to use Nutshell
Then the user should see a login screen
And they should enter their EMAIL and password
And they should be taken to their dashboard

## Technical Notes 

firebase.auth().signInWithEmailAndPassword(email, password).catch(function(error) {
  // Handle Errors here.
  var errorCode = error.code;
  var errorMessage = error.message;
  // ...
});

**Comment by michaelclark2** [comment]
```firebase.auth().signInWithEmailAndPassword(email, password).catch(function(error) {
  // Handle Errors here.
  var errorCode = error.code;
  var errorMessage = error.message;
  // ...
});```
